---
# From https://github.com/don-rumata/ansible-role-install-virtualbox

- name: Add repo GPG key
  when:
    - ansible_os_family == 'Debian'
    - ansible_virtualization_role == 'guest'
    - ansible_virtualization_type == 'virtualbox'
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
    - https://www.virtualbox.org/download/oracle_vbox.asc
    - https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc

- name: Add repo VirtualBox 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_virtualization_role == 'guest'
    - ansible_virtualization_type == 'virtualbox'
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] {{ http_or_https }}://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib non-free'
    state: present
    filename: virtualbox
