---
# From https://github.com/don-rumata/ansible-role-install-virtualbox

- name: Add repo VirtualBox 4 CentOS\RHEL
  when:
    - ansible_os_family == 'RedHat'
    - ansible_virtualization_role == 'guest'
    - ansible_virtualization_type == 'virtualbox'
  become: yes
  yum_repository:
    file: virtualbox
    name: virtualbox
    description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
    baseurl: '{{ http_or_https }}://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch'
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes
    gpgcheck: yes
    state: present
  tags:
    - linux
    - centos
    - virtualbox
    - repo
    - config
