---
  - name: Install Virtual Guest Agents
    hosts: all
    strategy: free
    serial:
      - "100%"
    tasks:

# hyper-v ubuntu
# https://gist.github.com/deoren/4d87ff5ddc831a22be433607341e5441
# https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v
# https://wiki.ubuntu.com/Hyper-V

# vmware windows
# https://packages.vmware.com/tools/releases/latest/windows/x64/
# http://partnerweb.vmware.com/programs/guestOS/guest-os-customization-matrix.pdf
# https://github.com/vmware/open-vm-tools
# https://community.chocolatey.org/packages/vmware-tools#files
# https://packages.vmware.com/tools/versions
# https://www.vmware.com/support/ws5/doc/ws_install_silent.html
# https://docs.vmware.com/en/VMware-Tools/11.3.0/com.vmware.vsphere.vmwaretools.doc/GUID-E45C572D-6448-410F-BFA2-F729F2CDA8AC.html

# https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub

# https://packages.vmware.com/tools/releases/latest/windows/x64/VMware-tools-11.3.0-18090558-x86_64.exe
# 11360       esx/0.0     		            11.3.0	    18090558
      # - name: parse html
      #   block:
      #     - uri:
      #         url: https://packages.vmware.com/tools/releases/latest/windows/x64/
      #         method: GET
      #         return_content: yes
      #       register: vmware_html
      #     - set_fact:
      #         vmware_html_fact: "{{ vmware_html.content | regex_findall('.*exe') | replace('<IMG SRC=\"/icons/generic.gif\" ALT=\"[FILE]\"> <A HREF=\"', '') }}"
      #     # Rewrite. I don't know how to do it in one step.
      #     - set_fact:
      #         vmware_html_fact: "{{ vmware_html_fact[0] }}"

# Win7 only. https://askubuntu.com/a/1355273/457538
virtual_guest_tools_virtio_win_win7_amd64_msi_url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.173-4/virtio-win-gt-x64.msi

# https://xenappblog.com/2018/download-and-install-latest-citrix-xenserver-tools/
# https://pvupdates.vmd.citrix.com/updates.latest.tsv

# TODO. Посмотреть тот ли это самый сертификат, который я храню в этой роли.
# https://fedorapeople.org/groups/virt/unattended/drivers/postinst/spice-guest-tools/0.141/
