---
- name: Enable QEMU guest agent 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
      or
      ansible_os_family == 'RedHat'
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - qemu-guest-agent
