---
- name: Enable Xen guest agent 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
  become: true
  service:
    name: xe-daemon.service
    enabled: true
    state: started

- name: Enable Xen guest agent 4 CentOS\RHEL\Fedora
  when:
    - ansible_os_family == 'RedHat'
  become: true
  service:
    name: xe-linux-distribution.service
    enabled: true
    state: started

- name: Enable Xen guest agent 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
  become: true
  service:
    name: xe-linux-distribution.service
    enabled: true
    state: started

- name: Enable Xen guest agent 4 Windows
  when:
    - ansible_os_family == 'Windows'
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_service:
    name: XenSvc
    start_mode: auto
    state: started
