---
# https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1614618/comments/6

# On hyper-v host\dom0:
# $MY_VM_NAME = 'buben2004'
# Enable-VMIntegrationService 'Guest Service Interface' -VMName $MY_VM_NAME
# Get-VMIntegrationService 'Guest Service Interface' -VMName $MY_VM_NAME

- name: Enable Hyper-V guest agent 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release != 'buster'
  become: true
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - hv-fcopy-daemon.service
    - hv-kvp-daemon.service
    - hv-vss-daemon.service

- name: Enable Hyper-V guest agent 4 Debian buster
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release == 'buster'
  become: true
  service:
    name: "hyperv-daemons.{{ item }}"
    enabled: true
    state: started
  with_items:
    - hv-fcopy-daemon.service
    - hv-kvp-daemon.service
    - hv-vss-daemon.service

- name: Enable Hyper-V guest agent 4 CentOS\RHEL\Fedora
  when:
      ansible_os_family == 'RedHat'
  become: true
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - hypervfcopyd.service
    - hypervkvpd.service
    - hypervvssd.service

- name: Enable Hyper-V guest agent 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
  become: true
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - hv_fcopy_daemon.service
    - hv_kvp_daemon.service
    - hv_vss_daemon.service

- name: Enable Hyper-V guest agent 4 Windows
  when:
    - ansible_os_family == 'Windows'
  become: true
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_service:
    name: "{{ item }}"
    start_mode: auto
    state: started
  with_items:
    - '{{ hyper_v_available_guest_serivces.stdout_lines }}'
