---
- name: Enable VMware guest agent 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
  become: true
  service:
    name: open-vm-tools.service
    enabled: true
    state: started

# Why does the service have such a crooked name?
# https://youtu.be/gqqm9CMKrA4
- name: Enable VMware guest agent 4 openSUSE\Fedora\RHEL
  when:
    - ansible_os_family == 'Suse'
      or
      ansible_os_family == 'RedHat'
  become: true
  service:
    name: vmtoolsd.service
    enabled: true
    state: started
