---
- name: Enable VMware guest agent 4 Debian\Ubuntu\Fedora\RHEL
  when:
    - ansible_os_family == 'Debian'
      or
      ansible_os_family == 'RedHat'
  become: yes
  service:
    name: open-vm-tools.service
    enabled: yes
    state: started

# Why does the service have such a crooked name?
# https://youtu.be/gqqm9CMKrA4
- name: Enable VMware guest agent 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
  become: yes
  service:
    name: vmtoolsd.service
    enabled: yes
    state: started
