---
- name: Enable Xen guest agent 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
  become: yes
  service:
    name: xe-daemon.service
    enabled: yes
    state: started

- name: Enable Xen guest agent 4 CentOS\RHEL\Fedora
  when:
    - ansible_os_family == 'RedHat'
  become: yes
  service:
    name: xe-linux-distribution.service
    enabled: yes
    state: started

# Why does the service have such a crooked name?
# https://youtu.be/gqqm9CMKrA4
- name: Enable Xen guest agent 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
  become: yes
  service:
    name: qemu-ga@virtio\x2dports-org.qemu.guest_agent.0.service
    enabled: yes
    state: started

- name: Enable Xen guest agent 4 Windows
  when:
    - ansible_os_family == 'Windows'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_service:
    name: XenSvc
    start_mode: auto
    state: started
