---
# https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1614618/comments/6

# On hyper-v host\dom0:
# $MY_VM_NAME = 'buben2004'
# Enable-VMIntegrationService 'Guest Service Interface' -VMName $MY_VM_NAME
# Get-VMIntegrationService 'Guest Service Interface' -VMName $MY_VM_NAME

- name: Enable Hyper-V guest agent 4 Debian\Ubuntu\Fedora\RHEL
  when:
    - ansible_os_family == 'Debian'
      or
      ansible_os_family == 'RedHat'
    - ansible_distribution_release != 'buster'
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - hv-fcopy-daemon.service
    - hv-kvp-daemon.service
    - hv-vss-daemon.service

- name: Enable Hyper-V guest agent 4 Debian buster
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release == 'buster'
  become: yes
  service:
    name: "hyperv-daemons.{{ item }}"
    enabled: yes
    state: started
  with_items:
    - hv-fcopy-daemon.service
    - hv-kvp-daemon.service
    - hv-vss-daemon.service

- name: Enable Hyper-V guest agent 4 openSUSE
  when:
    - ansible_os_family == 'Suse'
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - hv_fcopy_daemon.service
    - hv_kvp_daemon.service
    - hv_vss_daemon.service
