---
- name: Get service facts 4 Linux
  when: ansible_system == 'Linux'
  service_facts:

- name: Check VBoxService is installed
  when:
    - ansible_os_family == 'Windows'
    - ansible_virtualization_type == 'VirtualBox'
  win_service:
    name: VBoxService
  register: win_virtualbox_service_info

- name: Get VirtualBox available version
  when:
    - ansible_virtualization_type == 'virtualbox'
      or
      ansible_virtualization_type == 'VirtualBox'
  uri:
    url: '{{ virtualbox_url_version }}'
    method: GET
    return_content: yes
  register: virtualbox_available_version
  delegate_to: localhost

- name: Set facts about available virtualbox version
  when:
    - ansible_virtualization_type == 'virtualbox'
      or
      ansible_virtualization_type == 'VirtualBox'
  set_fact:
    virtualbox_available_version_fact:
      "{{ virtualbox_available_version.content
      | trim }}"
  delegate_to: localhost

- name: Set facts about virtualbox guest additions version
  when:
    - ansible_virtualization_type == 'virtualbox'
      or
      ansible_virtualization_type == 'VirtualBox'
  set_fact:
    virtualbox_guest_additions_iso_url_fact:
      '{{ virtualbox_url_path_to_iso }}'
  delegate_to: localhost

- name: Set facts about virtualbox guest additions filename
  when:
    - ansible_virtualization_type == 'virtualbox'
      or
      ansible_virtualization_type == 'VirtualBox'
  set_fact:
    virtualbox_guest_additions_iso_basename_fact:
      "{{ virtualbox_guest_additions_iso_url_fact
      | urlsplit('path')
      | basename }}"
  delegate_to: localhost
