---
- name: Configure pin file 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
  become: true
  copy:
    dest: /etc/apt/preferences.d/dependences-4-virtualbox
    mode: '644'
    content: |
      # https://unix.stackexchange.com/a/329843
      Package: fasttrack-archive-keyring
      Pin: release a={{ ansible_distribution_release }}-backports
      # Pin-Priority: -1
      Pin-Priority: 500

      Package: virtualbox-guest-dkms
      Pin: origin fasttrack.debian.net
      Pin-Priority: 500

      # https://wiki.debian.org/ru/AptPreferences#A.2BBB8EQAQ4BDwENQRHBDAEPQQ4BE8_.2BBD4EQg_ZugSchlus
      Package: virtualbox-guest-utils
      Pin: origin fasttrack.debian.net
      Pin-Priority: 500
    backup: true

# https://backports.debian.org/Instructions/
- name: Add repo backports 4 Debian Buster
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'
  become: true
  apt_repository:
    repo: deb {{ http_or_https }}://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
    state: present
    filename: '{{ ansible_distribution_release }}-backports'

- name: Install GPG keys 4 fasttrack repo 4 Debian
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'
  become: true
  package:
    name:
      - fasttrack-archive-keyring
    state: present

# https://fasttrack.debian.net/
# https://unix.stackexchange.com/a/286937
- name: Add repo fasttrak 4 Debian Buster
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: fasttrack
  with_items:
    - deb {{ http_or_https }}://fasttrack.debian.net/debian/ {{ ansible_distribution_release }}-fasttrack main contrib
    # - deb {{ http_or_https }}://fasttrack.debian.net/debian/ {{ ansible_distribution_release }}-backports main contrib

- name: Install VirtualBox guest utils 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
  become: true
  block:
    - package:
        name:
          - linux-headers-{{ ansible_kernel }}
          - virtualbox-guest-utils
        state: present
      register: virtualbox_guest_installed_status
    - package:
        name:
          - virtualbox-guest-dkms
        state: present
      when:
        - ansible_distribution == 'Ubuntu'
        - "ansible_distribution_version is version('22.04', '<')"

- name: Install VirtualBox guest gui utils 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_facts.services["display-manager.service"] is defined
    - ansible_facts.services["display-manager.service"].state == 'active'
  become: true
  package:
    name:
      - virtualbox-guest-x11
    state: present

- name: Once reboot, because it FUCKIN DIRTY HACK!!!
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'
    - virtualbox_guest_installed_status.changed
  become: true
  reboot:
