---
- name: Download VirtIO .cat 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_get_url:
    url: "{{ item }}"
    dest: '{{ ansible_env.TMP }}'
  with_items:
    - '{{ virtual_guest_tools_virtio_certs_urls }}'
  register: download_virtio_certs_result

# 2 install the spice client correctly
- name: Copy vioser.cat from ansible role to Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_copy:
    src: files/vioser.cat
    dest: '{{ ansible_env.TMP }}\'

- name: Get the paths of the downloaded certs
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  set_fact:
    download_virtio_certs_result_fact:
      "{{ download_virtio_certs_result
      | json_query(query_download_virtio_certs_result) }}"
  vars:
    query_download_virtio_certs_result:
      "results[].dest"

- name: Install VirtIO certs 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_certificate_store:
    path: "{{ item }}"
    state: present
    store_location: LocalMachine
    store_name: TrustedPublisher
  with_items:
    - '{{ download_virtio_certs_result_fact }}'
    - '{{ ansible_env.TMP }}\vioser.cat'

- name: Install QEMU guest agent 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_qemu_ga_win_amd64_msi_url }}'
    # product_id: QEMU guest agent
    creates_service: QEMU-GA
    state: present
    wait: true
  # register: qemu_ga_install_status

- name: Install SPICE guest tools 4 Windows 7
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
    - ansible_distribution_major_version == '6'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_virtio_win_win7_amd64_msi_url }}'
    # product_id: Virtio-win-driver-installer
    creates_service: BalloonService
    state: present
    wait: true
    arguments:
      - /S
  # register: spice_install_status

- name: Install VirtIO guest utils 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
    - ansible_distribution_major_version != '6'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_virtio_win_amd64_msi_url }}'
    # product_id: Virtio-win-driver-installer
    creates_service: BalloonService
    state: present
    wait: true
  # register: virtio_win_install_status

- name: Install SPICE webdavd 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_spice_webdavd_win_amd64_msi_url }}'
    # product_id: spice webdavd
    creates_service: spice-webdavd
    state: present
    wait: true
  # register: spice_webdavd_install_status

# - name: Reboot 4 QEMU GA start normally 4 Windows 7
#   when:
#     - ansible_os_family == 'Windows'
#     - ansible_system_vendor == 'QEMU'
#     - ansible_distribution_major_version == '6'
#     - qemu_ga_install_status.changed
#       or
#       spice_install_status.changed
#       or
#       spice_webdavd_install_status.changed
#   become: yes
#   become_method: runas
#   become_flags: logon_type=new_credentials logon_flags=netcredentials_only
#   win_reboot:

####################################################################

- name: Download csv-like file with guest utility versions 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'VMware, Inc.'
  uri:
    url: "{{ virtual_guest_tools_vmware_versions_url }}"
    return_content: yes
  register: vmware_csv_result
  delegate_to: localhost

# https://stackoverflow.com/a/1546244
- name: Set common fact 4 VMware from url content
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'VMware, Inc.'
  vars:
    var_regex_replace_comments: (^[^#].*$)
  set_fact:
    vmware_csv_result_fact:
      "{{ vmware_csv_result.content
      | regex_findall(var_regex_replace_comments, multiline=True)
      | replace('\\t', '')
      | regex_replace(' +', ' ') }}"

- name: Set the VMware version facts in detail
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'VMware, Inc.'
  set_fact:
    vmware_version_on_ngc_vi_client_fact:
      "{{ vmware_csv_result_fact[0].split(' ')[0] }}"
    vmware_esxi_server_version_fact:
      "{{ vmware_csv_result_fact[0].split(' ')[1] }}"
    vmware_esxi_server_build_number_fact:
      "{{ vmware_csv_result_fact[0].split(' ')[2] }}"
    vmware_tools_version_fact:
      "{{ vmware_tools_version
      | default(vmware_csv_result_fact[0].split(' ')[3]) }}"
    vmware_tools_build_number_fact:
      "{{ vmware_tools_build_number
      | default(vmware_csv_result_fact[0].split(' ')[4]) }}"

    # 4 debug
    # "vmware_csv_result_fact": [
    #     "11365 esx/6.7p06 18828794 11.3.5 18557794", 
    # ]

    # "ansible_facts": {
    #     "vmware_esxi_server_build_number_fact": "18828794", 
    #     "vmware_esxi_server_version_fact": "esx/6.7p06", 
    #     "vmware_tools_build_number_fact": "18557794", 
    #     "vmware_tools_version_fact": "11.3.5", 
    #     "vmware_version_on_ngc_vi_client_fact": "11365"

- name: Install VMware guest tools 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'VMware, Inc.'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_vmware_win_url }}'
    # product_id: VMware tools
    # creates_path: '%ProgramFiles%\VMware\VMware Tools\vmtoolsd.exe'
    # creates_version: "{{ vmware_tools_version_fact }} build-{{ vmware_tools_build_number_fact }}"
    creates_service: VMTools
    state: present
    arguments:
      # https://community.chocolatey.org/packages/vmware-tools#files
      - /S /v /qn REBOOT=R ADDLOCAL=ALL
  register: vmware_tools_install_result

- name: Reboot after install VMware guest tools 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'VMware, Inc.'
    - vmware_tools_install_result.reboot_required == virtual_guest_tools_vmware_win_reboot_after_install
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_reboot:

# 4 debug
# - win_file_version:
#     path: '%ProgramFiles%\VMware\VMware Tools\vmtoolsd.exe'
