---
- name: Download VirtIO .cat 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_get_url:
    url: "{{ item }}"
    dest: '{{ ansible_env.TMP }}'
  with_items:
    - '{{ virtual_guest_tools_virtio_certs_urls }}'
  register: download_virtio_certs_result

- name: Get the paths of the downloaded certs
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  set_fact:
    download_virtio_certs_result_fact:
      "{{ download_virtio_certs_result
      | json_query(query_download_virtio_certs_result) }}"
  vars:
    query_download_virtio_certs_result:
      "results[].dest"

- name: Install VirtIO certs 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_certificate_store:
    path: "{{ item }}"
    state: present
    store_location: LocalMachine
    store_name: TrustedPublisher
  with_items:
    - '{{ download_virtio_certs_result_fact }}'

- name: Install KVM guest utils 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_qemu_ga_win_amd64_msi_url }}'
    # product_id: QEMU guest agent
    creates_service: QEMU-GA
    state: present
    wait: true
  register: qemu_ga_install_status

# https://ovirt.org/documentation/virtual_machine_management_guide/#Installing_the_Guest_Agents_and_Drivers_on_Windows
# https://help.eset.com/eea/7/ru-RU/installation_command_line.html
- name: Install VirtIO guest utils 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ virtual_guest_tools_virtio_win_url_fact }}'
    # product_id: Virtio-win-driver-installer
    creates_service: BalloonService
    state: present
    wait: true
    arguments:
      # NOT work :(
      # - ADDEXCLUDE=FE_spice_Agent,FE_RHEV_Agent
      - /qn ADDLOCAL=FE_balloon_driver,FE_network_driver,FE_pvpanic_driver,FE_qemufwcfg_driver,FE_qemupciserial_driver,FE_qxl_driver,FE_spice_driver,FE_viorng_driver,FE_vioscsi_driver,FE_vioserial_driver,FE_viostor_driver

- name: Reboot 4 QEMU GA start normally 4 Windows 7
  when:
    - ansible_os_family == 'Windows'
    - ansible_system_vendor == 'QEMU'
    - ansible_distribution_major_version == '6'
    - qemu_ga_install_status.changed
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_reboot:
