---
- name: Download {{ virtualbox_guest_additions_iso_basename_fact }} 4 Windows
  when:
    - ansible_os_family == 'Windows'
    - not (win_virtualbox_service_info.exists)
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    vboxguestadditions_full_path_to_save:
      '{{ ansible_env.TMP }}\{{ virtualbox_guest_additions_iso_basename_fact }}'
  win_get_url:
    url: '{{ virtualbox_guest_additions_iso_url_fact }}'
    dest: '{{ vboxguestadditions_full_path_to_save }}'

- name: Ensure an ISO is mounted
  when:
    - ansible_os_family == 'Windows'
    - ansible_distribution_major_version == '10'
    - not (win_virtualbox_service_info.exists)
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    vboxguestadditions_full_path_to_save:
      '{{ ansible_env.TMP }}\{{ virtualbox_guest_additions_iso_basename_fact }}'
  win_disk_image:
    image_path: '{{ vboxguestadditions_full_path_to_save }}'
    state: present
  register: disk_image_out

- name: Add trusted certificates to local machine
  when:
    - ansible_os_family == 'Windows'
    - ansible_distribution_major_version == '10'
    - not (win_virtualbox_service_info.exists)
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_certificate_store:
    # path: \\10.10.10.10\drivers\other\virtualbox\cert\{{ item }}
    path: '{{ disk_image_out.mount_path }}\cert\{{ item }}'
    state: present
    store_location: LocalMachine
    store_name: TrustedPublisher
  with_items:
    - vbox-sha1.cer
    - vbox-sha256.cer

- name: Install VirtualBox Guest Additions
  when:
    - ansible_os_family == 'Windows'
    # - ansible_distribution_major_version == '10'
    - not (win_virtualbox_service_info.exists)
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_package:
    path: '{{ disk_image_out.mount_path }}\vboxwindowsadditions-{{ ansible_env.PROCESSOR_ARCHITECTURE }}.exe'
    # product_id: 'Oracle VM VirtualBox Guest Additions {{ virtualbox_available_version_fact }}'
    creates_service: VBoxService
    arguments:
      - /force /with_autologon /with_wddm /S
