---
- name: Install VMware guest utils 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
  become: yes
  package:
    name:
      - open-vm-tools
    state: present

# https://ru.stackoverflow.com/a/1376272/191416
# https://stackoverflow.com/a/65027270
- name: Install VMware guest gui utils 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_facts.services["display-manager.service"] is defined
    - ansible_facts.services["display-manager.service"].state == 'active'
  become: yes
  package:
    name:
      - open-vm-tools-desktop
    state: present
