---
- name: Install VirtualBox guest utils 4 Ubuntu
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_system_vendor == 'innotek GmbH'
    - ansible_virtualization_type == 'virtualbox'
    - ansible_virtualization_role == 'guest'
  become: yes
  block:
    - apt:
        name:
          - virtualbox-guest-dkms
          - virtualbox-guest-utils
          - virtualbox-guest-x11
        state: latest
        install_recommends: yes
# TODO. Подумать как реализовать. Вернее - на что опираться. Чё-то я очередной раз туплю.
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html
#    - apt:
#        name: virtualbox-guest-x11
#        state: latest
#        install_recommends: yes
#      when: ГРАФОН_УСТАНОВЛЕН_И_ВКЛЮЧЕН == 'Тру'
# При первом запуске сразу после установки может не отпахать. Надо ребутнуть тачку. Я пока хз как это отпарсить.
    - service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - virtualbox-guest-utils.service
