---
# https://linuxhint.com/install-virtualbox-guest-additions-centos/
# https://stackoverflow.com/a/30120360/5430535
- name: Add EPEL repo 4 CentOS 8+
  when:
    - ansible_distribution == "CentOS"
    # - ansible_distribution_major_version == '8'
    - ansible_virtualization_role == 'guest'
    - ansible_facts.services['vboxadd-service.service'] is not defined
      or
      ansible_facts.services['vboxadd-service.service'].state != 'running'
  become: yes
  package:
    name:
      - epel-release
    state: present

- name: Install dependencies 4 run VBoxLinuxAdditions.run
  when:
    - ansible_distribution == 'CentOS'
    - ansible_virtualization_role == 'guest'
    - ansible_facts.services['vboxadd-service.service'] is not defined
      or
      ansible_facts.services['vboxadd-service.service'].state != 'running'
  become: yes
  package:
    name:
      - gcc
      - kernel-devel
      - kernel-headers
      - dkms
      - make
      - bzip2
      - perl
    state: present

- name: Install virtualbox-guest-additions 4 Fedora
  when:
    - ansible_distribution == "Fedora"
    - ansible_virtualization_role == 'guest'
  become: yes
  package:
    name:
      - virtualbox-guest-additions
    state: present

- include_tasks: install-guest-tools-4-virtualbox-from-iso.yml
  when:
    - ansible_system == 'Linux'
    - ansible_distribution == "CentOS"
    # - ansible_distribution_major_version == '8'
    - ansible_virtualization_role == 'guest'
