---
- name: Install dependencies 4 run VBoxLinuxAdditions.run
  when:
    - ansible_distribution == "Debian"
    - ansible_virtualization_role == 'guest'
    # - ansible_facts.services['vboxadd-service.service'] is not defined
    #   or
    #   ansible_facts.services['vboxadd-service.service'].state != 'running'
  become: yes
  package:
    name:
      - linux-headers-{{ ansible_kernel }}
    state: present

- name: Config dependences config file 4 Ubuntu 18.04, Debian 10
  when:
    - ansible_os_family == 'Debian'
    - ansible_virtualization_role == 'guest'
  become: yes
  copy:
    dest: /etc/apt/preferences.d/dependences-4-virtualbox
    mode: '644'
    content: |
      # https://askubuntu.com/a/1205535
      Package: virtualbox-guest-dkms
      Pin: origin deb.debian.org release a=sid
      Pin-Priority: 500

      # https://wiki.debian.org/ru/AptPreferences#A.2BBB8EQAQ4BDwENQRHBDAEPQQ4BE8_.2BBD4EQg_ZugSchlus
      Package: virtualbox-guest-utils
      Pin: origin deb.debian.org release a=sid
      Pin-Priority: 500

# https://unix.stackexchange.com/a/286937
# https://packages.debian.org/search?suite=all&arch=any&searchon=names&keywords=virtualbox
- name: Add repo sid backports 4 Debian
  when:
    - ansible_distribution == "Debian"
    - ansible_virtualization_role == 'guest'
  become: yes
  apt_repository:
    repo: 'deb {{ http_or_https }}://deb.debian.org/debian sid main contrib non-free'
    state: present
    filename: sid

- name: Install VirtualBox guest utils
  when:
    - ansible_os_family == 'Debian'
    - ansible_virtualization_role == 'guest'
  become: yes
  package:
    name:
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
      # TODO. https://ru.stackoverflow.com/q/1113754
      # - virtualbox-guest-x11
    state: present

# - include_tasks: install-guest-tools-4-virtualbox-from-iso.yml
#   when:
#     - ansible_system == 'Linux'
#     - ansible_distribution == "Debian"
#     # - ansible_distribution_major_version == '8'
#     - ansible_virtualization_role == 'guest'
