---
# https://support.microsoft.com/en-us/topic/hyper-v-integration-components-update-for-windows-virtual-machines-8a74ffad-576e-d5a0-5a2f-d6fb2594f990
# https://www.microsoft.com/en-us/download/details.aspx?id=51901
# https://gcits.com/knowledge-base/manually-install-integration-tools-hyper-v-virtual-machine/
# win7-64 https://download.microsoft.com/download/0/C/A/0CADD11C-CE3A-4BF6-8321-165438638676/windows6.x-hypervintegrationservices-x64.cab
# Add-WindowsPackage -Online -PackagePath $integrationServicesCabPath

- name: Get installed Windows updates
  when:
    - ansible_os_family == 'Windows'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_shell: Get-HotFix | select -ExpandProperty HotFixID | ConvertTo-Json -Compress
  args:
    executable: powershell
  register: win_kb_installed
  changed_when: false

- name: Find KB3063109 in installed KB
  when:
    - ansible_os_family == 'Windows'
  set_fact:
    installed_kb_for_guest_hyper_v_fact:
      "{{ win_kb_installed.stdout
      | from_json
      | json_query(query_installed_kb_for_guest_hyper_v) }}"
  vars:
    query_installed_kb_for_guest_hyper_v:
      # "[?contains(@, 'KB3063109') == `true`]"
      "[?contains(@, 'KB4516065')] | [0]"
      # "[?contains(@, '4516065') == `true`] | [0]"

- pause:

- name: Start Windows update service
  when:
    - ansible_os_family == 'Windows'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_service:
    name: "{{ item }}"
    start_mode: auto
    state: started
  with_items:
    - wuauserv
    # - UsoSvc

- name: Install only particular updates based on the KB numbers
  when:
    - ansible_os_family == 'Windows'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  win_updates:
    # category_name:
    # - SecurityUpdates
    whitelist:
    - KB3063109
