---
# https://software.opensuse.org/package/virtualbox-guest-tools
- name: Install VirtualBox guest utils 4 openSUSE
  when:
    - ansible_system == 'Linux'
  become: true
  package:
    name:
      - virtualbox-guest-tools
      - virtualbox-kmp-default
      # TODO. https://ru.stackoverflow.com/q/1113754
      # - virtualbox-guest-x11
    state: present
