---
- include_tasks: update-cache.yml
  when: ansible_virtualization_type == 'docker'

- import_tasks: install-dependencies.yml

- include_tasks: set-facts.yml

- include_tasks: get-info-and-set-facts.yml

- include_tasks: install-guest-tools-4-{{ ansible_virtualization_type | lower }}-{{ ansible_os_family | lower }}.yml

- include_tasks: enable-guest-agent-service-4-{{ ansible_virtualization_type | lower }}.yml
